### ISSUE TITLE
分模块是view地址怎么动态分配

### ISSUE THREAD

**Issue by SkyPl** [justmd5/yaf-twig-adapter#1]
protected function _initTwig(Dispatcher $dispatcher)
    {
        $config = Application::app()->getConfig();
        $dispatcher->setView(new Twig(APP_PATH.'views', $config->twig->toArray()));
    }

这里在默认的view里可以使用，但是如果在modules里有其他的模块（eg：Admin）那么views的默认地址是Application/modules/Admin/views，这样的话这个设置就不能使用了，要怎么处理呢?

**Comment by justmd5** [comment]
稍后我修改下模板配置这块的，兼容多modules情况

**Comment by justmd5** [comment]
@Typl 稍后我修改下模板配置这块的，兼容多modules情况

**Comment by justmd5** [comment]
fixed https://github.com/justmd5/yaf-twig-adapter/commit/56281c5d17d4f2cf73d410135a79d99ee0d30707
